# Generated by Django 5.1.4 on 2025-01-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_basefile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
